apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: configuration-piraeus
  annotations:
    meta.crossplane.io/maintainer: Livewyer <bowen@livewyer.com>
    meta.crossplane.io/source: github.com/livewyer-ops/crossplane-configuration-piraeus
    meta.crossplane.io/license: MIT License
    meta.crossplane.io/description: Crossplane Configuration to deploy and manage Piraeus/Linbit datastore on Kubernetes.
    meta.crossplane.io/readme: |
      ## Installation
      You can install the configuration package directly from the Upbound registry:
      ```sh
      crossplane xpkg install configuration xpkg.upbound.io/nusnewob/configuration-piraeus:v0.0.1 configuration-piraeus
      ```
      ## Usage
      1. **Install Crossplane** on your Kubernetes cluster.
      2. **Set up provider credentials** using providerconfig.yaml for cluster-wide permissions required to manage StorageClass and Piraeus resources.
      3. Apply the composite definitions:
        ```sh
        kubectl apply -f examples/install.yaml
        kubectl apply -f examples/cluster.yaml
        ```
      ## Examples
      - The [`examples/`](examples/) folder contains sample configuration files for setting up Piraeus resources.
      - Ensure [`providerconfig.yaml`](examples/providerconfig.yaml) is configured for managing Kubernetes storage classes and Piraeus resources.

spec:
  crossplane:
    version: ">=v1.19.0"
  dependsOn:
    - provider: xpkg.upbound.io/upbound/provider-helm
      version: ">=v0"
    - function: xpkg.upbound.io/upbound/function-patch-and-transform
      version: ">=v0.8.2"
    - function: xpkg.upbound.io/upbound/function-go-templating
      version: ">=v0.9.2"
    - function: xpkg.upbound.io/upbound/function-auto-ready
      version: ">=v0.4.2"
