apiVersion: meta.dev.upbound.io/v1alpha1
kind: Project
metadata:
  name: configuration-piraeus
spec:
  description: This is where you can describe your project.
  license: Apache-2.0
  maintainer: Upbound User <user@example.com>
  readme: |
    This is where you can add a readme for your project.
  repository: xpkg.upbound.io/nusnewob/configuration-piraeus
  source: github.com/upbound/project-template
