apiVersion: piraeus.livewyer.io/v1alpha1
kind: Installation
metadata:
  namespace: piraeus-full
spec:
  charts:
    - name: piraeus
      namespace: piraeus-datastore
      repository: https://livewyer-ops.github.io/charts/
      values:
        installCRDs: true
    - name: linstor-affinity-controller
      namespace: piraeus-datastore
      repository: https://piraeus.io/helm-charts/
    - name: linstor-scheduler
      namespace: piraeus-datastore
      repository: https://piraeus.io/helm-charts/
    - name: snapshot-controller
      namespace: snapshot-controller
      repository: https://piraeus.io/helm-charts/
    - name: cert-manager
      namespace: cert-manager
      repository: https://charts.jetstack.io/
      values:
        crds:
          enabled: true

---
apiVersion: piraeus.livewyer.io/v1alpha1
kind: Cluster
metadata:
  name: test-linstor-cluster
spec:
  cluster:
    highAvailabilityController:
      enabled: true
  nodeConnection: {}
  satelliteConfiguration: {}
  storagePools:
    - name: pool1
      spec:
        type: fileThinPool
        directory: /var/lib/linstor/pools/pool1
      storageClass:
        spec:
          allowVolumeExpansion: true
    - name: pool2
      spec:
        type: fileThinPool
        directory: /var/lib/linstor/pools/pool2
      storageClass:
        spec:
          allowVolumeExpansion: true
          parameters:
            linstor.csi.linbit.com/placementCount: "2"
