apiVersion: piraeus.livewyer.io/v1alpha1
kind: Cluster
metadata:
  name: demo
spec:
  cluster:
    highAvailabilityController:
      enabled: true
  # nodeConnection: {}
  # satelliteConfiguration: {}
  storagePools:
    - name: pool1
      type: fileThinPool
      spec:
        directory: /var/lib/linstor/pools/pool1
      storageClass:
        allowVolumeExpansion: true
    - name: pool2
      type: fileThinPool
      spec:
        directory: /var/lib/linstor/pools/pool2
      storageClass:
        allowVolumeExpansion: true
        parameters:
          linstor.csi.linbit.com/placementCount: "2"
