apiVersion: piraeus.livewyer.io/v1alpha1
kind: Installation
metadata:
  name: piraeus
spec:
  charts:
    piraeus:
      version: 2.8.0
    snapshot-controller:
      namespace: snapshot-controller
      repository: https://piraeus.io/helm-charts/
