apiVersion: piraeus.livewyer.io/v1alpha1
kind: Installation
metadata:
  name: piraeus
spec:
  charts:
    piraeus:
      version: 2.8.0
    linstor-affinity-controller:
      namespace: piraeus-datastore
      repository: https://piraeus.io/helm-charts/
