apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: installation.piraeus.livewyer.io
spec:
  compositeTypeRef:
    apiVersion: piraeus.livewyer.io/v1alpha1
    kind: Installation
  mode: Pipeline
  pipeline:
    - step: go-templating
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{ $id := .observed.composite.resource.metadata.name }}
            {{ $spec := .observed.composite.resource.spec }}

            {{- $charts := list }}
            {{- $charts = append $charts (dict "name" "piraeus" "namespace" "piraeus-datastore" "repository" "https://livewyer-ops.github.io/charts/" "values" "installCRDs: true") }}
            {{- $charts = append $charts (dict "name" "linstor-affinity-controller" "namespace" "piraeus-datastore" "repository" "https://livewyer-ops.github.io/charts/") }}
            {{- $charts = append $charts (dict "name" "linstor-scheduler" "namespace" "piraeus-datastore" "repository" "https://livewyer-ops.github.io/charts/") }}

            {{- range $index, $chart := default $charts $spec.charts }}
            apiVersion: helm.crossplane.io/v1beta1
            kind: Release
            metadata:
              name: {{ $id }}-{{ $chart.name }}
              annotations:
                {{ setResourceNameAnnotation (printf "release.helm.crossplane.io/%s-%s" $id $chart.name) }}
              labels:
                piraeus.livewyer.io/installation: {{ $id }}
            spec:
              forProvider:
                chart:
                  name: {{ $chart.name }}
                  {{- if $chart.repository }}
                  repository: {{ $chart.repository }}
                  {{- end }}
                  {{- if $chart.version }}
                  version: {{ $chart.version }}
                  {{- end }}
                  {{- if $chart.url }}
                  url: {{ $chart.url }}
                  {{- end }}
                  {{- if $chart.pullSecretRef }}
                  pullSecretRef:
                    name: {{ $chart.pullSecretRef.name }}
                    namespace: {{ $chart.pullSecretRef.namespace }}
                  {{- end }}
                namespace: {{ $chart.namespace }}
                {{- if $chart.skipCRDs}}
                skipCRDs: {{ $chart.skipCRDs }}
                {{- end }}
                {{- if $chart.skipCreateNamespace }}
                skipCreateNamespace: {{ $chart.skipCreateNamespace }}
                {{- end }}
                {{- if $chart.wait }}
                wait: {{ $chart.wait }}
                {{- end }}
                {{- if $chart.waitTimeout }}
                waitTimeout: {{ $chart.waitTimeout }}
                {{- end }}
                {{- if $chart.rollbackLimit }}
                rollbackLimit: {{ $chart.rollbackLimit }}
                {{- end }}
                {{- if $chart.values }}
                values:
                  {{ toYaml $chart.values | indent 6 }}
                {{- end }}
                {{- if $chart.patchesFrom }}
                patchesFrom:
                  {{ toYaml $chart.patchesFrom | indent 6 }}
                {{- end }}
                {{- if $chart.set}}
                set:
                  {{ toYaml $chart.set | indent 6 }}
                {{- end }}
                {{- if $chart.valuesFrom }}
                valuesFrom:
                  {{ toYaml $chart.valuesFrom | indent 6 }}
                {{- end }}
            ---
            {{- end }}
    - step: automatically-detect-readiness
      functionRef:
        name: function-auto-ready

---
apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: cluster.piraeus.livewyer.io
spec:
  compositeTypeRef:
    apiVersion: piraeus.livewyer.io/v1alpha1
    kind: Cluster
  mode: Pipeline
  pipeline:
    - step: go-templating
      functionRef:
        name: function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            {{ $id := .observed.composite.resource.metadata.name }}
            {{ $spec := .observed.composite.resource.spec }}

            apiVersion: piraeus.io/v1
            kind: LinstorCluster
            metadata:
              name: {{ $id }}
              annotations:
                {{ setResourceNameAnnotation (printf "cluster.piraeus.livewyer.io/%s" $id) }}
              labels:
                piraeus.livewyer.io/cluster: {{ $id }}
            spec:
              {{- if $spec.cluster }}
              {{ toYaml $spec.cluster | indent 2 }}
              {{- else }}
              {}
              {{- end }}

            ---
            {{- if $spec.nodeConnection }}
            apiVersion: piraeus.io/v1
            kind: LinstorNodeConnection
            metadata:
              name: {{ $id }}
              annotations:
                {{ setResourceNameAnnotation (printf "cluster.piraeus.livewyer.io/%s" $id) }}
              labels:
                piraeus.livewyer.io/cluster: {{ $id }}
            spec:
              {{ toYaml $spec.nodeConnection | indent 2 }}

            ---
            {{- end }}

            apiVersion: piraeus.io/v1
            kind: LinstorSatelliteConfiguration
            metadata:
              name: {{ $id }}
              annotations:
                {{ setResourceNameAnnotation (printf "cluster.piraeus.livewyer.io/%s" $id) }}
              labels:
                piraeus.livewyer.io/cluster: {{ $id }}
            spec:
              {{- if $spec.satelliteConfiguration }}
              {{ toYaml $spec.satelliteConfiguration | indent 2 }}
              {{- end }}
              storagePools:
                {{- range $index, $pool := $spec.storagePools }}
                - name: {{ $pool.name }}
                  {{ $pool.type }}:
                    {{ toYaml $pool.spec | indent 8 }}
                {{- end }}

            ---
            {{- range $index, $pool := $spec.storagePools }}

            apiVersion: storage.k8s.io/v1
            kind: StorageClass
            metadata:
              name: {{ $id }}-{{ $pool.name }}
              annotations:
                {{ setResourceNameAnnotation (printf "cluster.piraeus.livewyer.io/%s" $id) }}
              labels:
                piraeus.livewyer.io/cluster: {{ $id }}
            spec:
              {{- if $pool.storageClass }}
              {{ toYaml $pool.storageClass | indent 2 }}
              {{- else }}
              {}
              {{- end }}

            ---
            {{- end }}

    - step: automatically-detect-readiness
      functionRef:
        name: function-auto-ready
