name: CI

on:
  push:
    branches:
      - main
    tags:
      - "**"
  pull_request: {}

env:
  UP_API_TOKEN: ${{ secrets.UP_API_TOKEN }}
  UP_ORG: ${{ secrets.UP_ORG }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - uses: actions-ecosystem/action-get-latest-tag@v1.6.0
        id: get-latest-tag
        if: ${{ github.ref_type != 'tag' }}

      - uses: actions-ecosystem/action-bump-semver@v1
        id: bump-semver
        if: ${{ github.ref_type != 'tag' }}
        with:
          current_version: ${{ steps.get-latest-tag.outputs.tag }}

      - name: Get release version
        run: |
          echo RELEASE=$([[ ${GITHUB_REF_TYPE} == "tag" ]] && echo ${GITHUB_REF_NAME} || echo ${{ steps.bump-semver.outputs.new_version }}-${GITHUB_SHA::7}) >> $GITHUB_ENV

      - name: Install and login with up
        if: env.UP_API_TOKEN != '' && env.UP_ORG != ''
        uses: upbound/action-up@v1
        with:
          api-token: ${{ secrets.UP_API_TOKEN }}
          organization: ${{ secrets.UP_ORG }}

      - name: Build and Push Upbound project
        if: env.UP_API_TOKEN != ''
        uses: upbound/action-up-project@v1
        with:
          push-project: true
          tag: ${{ env.RELEASE }}
